### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ainsoflv** [Mrzqd/52pojie_sign#1]
## 开始执行... 2023-01-30 21:20:04

Traceback (most recent call last):

  File "raw_youth_52pojie.swap.py", line 35, in <module>

    
jx_data = r_data.find("div", id="messagetext").find("p").text

AttributeError: 'NoneType' object has no attribute 'find'

## 执行结束... 2023-01-30 21:20:05 耗时 1 秒

**Comment by fluffy90s** [comment]
一样错误：
File "/ql/data/scripts/52pojie_Sign.py", line 34, in <module>

    jx_data = r_data.find("div", id="messagetext").find("p").text
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by Mrzqd** [comment]
好兄弟，更新了，再试试

**Comment by Mrzqd** [comment]
> 一样错误： File "/ql/data/scripts/52pojie_Sign.py", line 34, in
> 
> ```
> jx_data = r_data.find("div", id="messagetext").find("p").text
> ```
> 
> AttributeError: 'NoneType' object has no attribute 'find'


好兄弟，更新了，再试试

**Comment by Mrzqd** [comment]
> 一样错误： File "/ql/data/scripts/52pojie_Sign.py", line 34, in
> 
> ```
> jx_data = r_data.find("div", id="messagetext").find("p").text
> ```
> 
> AttributeError: 'NoneType' object has no attribute 'find'


好兄弟，更新了，再试试
