### ISSUE TITLE
KeyError: 'set-cookie'

### ISSUE THREAD

**Issue by ainsoflv** [Mrzqd/52pojie_sign#2]
File "/app/52pojie.py", line 43, in <module>
    s_cookie = r.headers['Set-Cookie']
  File "/usr/local/lib/python3.10/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'
成功运行是这样，前提是得安装bs4包。可以在上面增加：【
import sys
import os
try:
    from bs4 import BeautifulSoup
except ModuleNotFoundError:
    print("缺少BeautifulSoup依赖！程序将尝试安装依赖！")
    os.system("pip3 install BeautifulSoup4 -i https://pypi.tuna.tsinghua.edu.cn/simple")
    os.execl(sys.executable, 'python3', __file__, *sys.argv)
】
自动安装此依赖。
但安装了后，还是出现上面keyeeror。

**Comment by Mrzqd** [comment]
说明您的cookie不正确，用您的cookie去访问动态cookie时候没有返回动态的cookie，请检查你的cookie格式，一般只需要我在主页写的那两个字段就行了
